### ISSUE TITLE
Identify World Time API

### ISSUE THREAD

**Issue by thebobfather2** [thebobfather2/carrotcalendar#10]
# Step 2: World Time API
Figure out which API we will use for world time

**Comment by larigens** [comment]
https://www.abstractapi.com/api/time-date-timezone-api#docs

**Comment by larigens** [comment]
http://worldtimeapi.org/

This one looks more simple

**Comment by sarahgjacobs** [comment]
This is one I found that looks straight forward: timezonedb.com

**Comment by thebobfather2** [comment]
sarah got this working!
